name: "Run Unit Test"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Golang Unit Test
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./go
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create default dir config file
        shell: bash
        env:
          TEST_CONFIG: ${{ secrets.TEST_CONFIG }}
        run: |
          echo "$TEST_CONFIG" > ./config.json
      - name: Test 1
        run: go test ./...
      - name: Create alternate dir config file
        shell: bash
        run: |
          mkdir config
          mv ./config.json ./config/config.json
      - name: Test 2
        run: go test ./...
