name: "Run Unit Test"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Test
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create default dir config file
        shell: bash
        env:
          TEST_CONFIG: ${{ secrets.TEST_CONFIG }}
        run: |
          echo "$TEST_CONFIG" > ./config.test.json
      - name: Test 1
        run: go test ./...
      - name: Create alternate dir config file
        shell: bash
        run: |
          mkdir config
          mv ./config.test.json ./config/config.test.json
      - name: Test 2
        run: go test ./...
